### ISSUE TITLE
Change apps' ports to be more intuitive to each vulnerability

### ISSUE THREAD

**Issue by rafaveira3** [globocom/secDevLabs#164]
In most of our apps, the ports were chosen randomly, which might leave people lost as to which port to access to get to the action.

In order to standardize all of our apps, it would be great if we could change the ports to this pattern:
* A1 App - Port : 10001
* A2 App - Port: 10002
* A3 App - Port: 10003
* A4 App - Port: 10004
* A5 App - Port: 10005
* A6 App - Port: 10006
* A7 App - Port: 10007
* A8 App - Port: 10008
* A9 App - Port: 10009
* A10 App - Port: 10010

**Comment by n8eloy** [comment]
Good morning! 

I've opened a PR about this issue. Please feel free to point out any mistake!
