### ISSUE TITLE
Login and Register routes in A1 CopyNPaste app returns 405

### ISSUE THREAD

**Issue by Takehime** [globocom/secDevLabs#228]
After building CopyNPaste app and sending a login or register request through the web interface buttons, a `405 Method Not Allowed` message is returned. 

This seems to happen only on the application's web interface. If we use curl the application works as intended as shown below.

**Request:**
```sh 
curl -s -H "Content-Type: application/json" -d '{"user":"test", "pass":"test"}' http://127.0.0.1:3000/login
```
**Response:** 
```sh 
User not found or wrong password!
```

**Comment by Krlier** [comment]
I wasn't able to reproduce this bug, @Takehime. Could you provide the API's log, please?

**Comment by Takehime** [comment]
Well, it seems to be working now. 🤷‍♀️
I'll close this issue for now, thanks.
