### ISSUE TITLE
Add web interface to insecure-go-project App

### ISSUE THREAD

**Issue by Krlier** [globocom/secDevLabs#276]
Nowadays the app is can only be used through the terminal:

![image](https://user-images.githubusercontent.com/40367872/66069601-07916d80-e526-11e9-82bc-4f3da907c555.png)

It would be great if we could add a web interface to the [insecure-go-project](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a2/insecure-go-project) such as these apps:

![image](https://user-images.githubusercontent.com/40367872/66070910-91423a80-e528-11e9-9c00-51e0c8e3d3cd.png)
![image](https://user-images.githubusercontent.com/40367872/66070933-9bfccf80-e528-11e9-9930-9d15ea92deda.png)

**Comment by alcoelho** [comment]
Hey! Can I get this issue?

**Comment by Krlier** [comment]
> Hey! Can I get this issue?

Definitely!

**Comment by cleisoncarlos** [comment]
How can i help? with design

**Comment by Krlier** [comment]
> How can i help? with design

Yes! You can help by creating a web interface to the [Insecure-go-project](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a2/insecure-go-project) app! Nowadays, this app works only through the command line.

**Comment by Krlier** [comment]
Hey @cleisoncarlos and @alcoelho, I'm closing this issue for now due to the long inactivity.

If you're still working on this, please let me know and we'll reopen this issue! 🙂
