### ISSUE TITLE
Create another app for A1 - Injection

### ISSUE THREAD

**Issue by Takehime** [globocom/secDevLabs#277]
We currently only have one app for A1 (Injection) topic containing an SQL Injection vulnerability. Since Injection is a big topic, it would be awesome if we had another application approaching a different type of Injection, like: 

- [Command Injection](https://cwe.mitre.org/data/definitions/77.html)
- [Server-side Template Injection](https://portswigger.net/kb/issues/00101080_server-side-template-injection)
- [NOSQL Injection](https://erlend.oftedal.no/blog/static-110.html?blogid=110) 

and many more!

This new app could also be written in a different language than the current one (Golang). Some suggestions are:
- Ruby
- Python
- Java

You can check our [Contributing Guidelines](https://github.com/globocom/secDevLabs/blob/master/docs/CONTRIBUTING.md) on creating a new app.

**Comment by vitor-fernandes** [comment]
Hi, I have a application with NoSQL (MongoDB) Injection example, I'll submit a PR with the application.

**Comment by rafaveira3** [comment]
Awesome, @vitor-fernandes! 🚀 Sounds great a NoSQL example! Let us know if you need any help on the attack narrative, docker-compose, etc.

**Comment by vitor-fernandes** [comment]
Thanks for helping. I think that I got do it, sent a PR with the application

**Comment by vitor-fernandes** [comment]
Hey, if possible I can do 2 more applications with Command Injection and SSTI :)

**Comment by Takehime** [comment]
That would be great @vitor-fernandes!! We'll be reviewing your NoSQL app soon!

**Comment by v0idpwn** [comment]
Hey, I've a concluded command injection example. Should I PR it? :)
