### ISSUE TITLE
Create another app for A3 - Sensitive Data Exposure

### ISSUE THREAD

**Issue by spimpaov** [globocom/secDevLabs#278]
Currently we have only one app for this topic written in Golang. It would be awesome having another application with a different language for this topic. Some suggestions are: 
- Ruby
- Python
- Java

You can check our [Contributing Guidelines](https://github.com/globocom/secDevLabs/blob/master/docs/CONTRIBUTING.md) on creating a new app.
If you want to learn more about this topic, a very good reference would be [OWASP's page](https://www.owasp.org/index.php/Top_10-2017_A3-Sensitive_Data_Exposure).

**Comment by danielmitre** [comment]
I've seen a nice one recently and I will try to reproduce it in NodeJS.
