### ISSUE TITLE
Create another app for A7 - Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by spimpaov** [globocom/secDevLabs#280]
Currently we have only one app for this topic written in Python. It would be awesome having another application with a different language for this topic. Some suggestions are: 
- Ruby
- Golang
- Java

You can check our [Contributing Guidelines](https://github.com/globocom/secDevLabs/blob/master/docs/CONTRIBUTING.md) on creating a new app.
If you want to learn more about this topic, a very good reference would be [OWASP's page](https://www.owasp.org/index.php/Top_10-2017_A7-Cross-Site_Scripting_(XSS)).

**Comment by v0idpwn** [comment]
Can I get this one? :)

**Comment by Takehime** [comment]
Sure, @v0idpwn!

**Comment by v0idpwn** [comment]
@Takehime do I still get a shirt if I finish this november 1? 🤭
