### ISSUE TITLE
Create a container with all tools needed to perform the analyses

### ISSUE THREAD

**Issue by Krlier** [globocom/secDevLabs#284]
Through some of the apps, such as [CopyNPaste API](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a1/copy-n-paste), [Vulnerable Wordpress Misconfig](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a6/misconfig-wordpress), [Stegonography](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a6/stegonography) and [Amarelo Designs](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a8/amarelo-designs), the following tools are used to perform automated tasks: [SQLMap](http://sqlmap.org/), [WPScan](https://wpscan.org/) and [Dirb](https://tools.kali.org/web-applications/dirb).

Sometimes it can be a hassle for people to properly install these tools, some can be quite challenging to install on Mac OS. With that in mind, it would be great if we could build a container with all these security tools already installed and ready to go. Having that, all a developer would need to do is run the container and use the tools on the intentionally vulnerable apps of secDevLabs.

**Comment by pedroespindula** [comment]
I can try to do this issue. Also, congrats for the repo! it's really good!

**Comment by pedroespindula** [comment]
Just a doubt, the container will be a development environment that the user will enter on it and have all the tools needed? or the container will have all tools available and you access them from the outside of the container?

**Comment by Krlier** [comment]
> Just a doubt, the container will be a development environment that the user will enter on it and have all the tools needed? or the container will have all tools available and you access them from the outside of the container?

I believe that if the users could access the container and use the tools from within it, it would be easier for them. In this scenario, some docker networking changes must happen as well, so users can easily use the tools as if they were installed in their own host system.

**Comment by sagar-cs03** [comment]
Hi @Krlier, I started working on it yesterday and thought I'll update it once I create the container. I created one and it's now at https://cloud.docker.com/repository/registry-1.docker.io/sagarcs/security-tools. Please check if it's okay or you need any other changes.

**Comment by Krlier** [comment]
> Hi @Krlier, I started working on it yesterday and thought I'll update it once I create the container. I created one and it's now at https://hub.docker.com/r/sagarcs/security-tools Please check if it's okay or you need any other changes.

Thanks, @sagar-cs03! That's along the lines of what I was looking for, but could you also provide the dockerfile for the container?

**Comment by sagar-cs03** [comment]
@Krlier I started with an ubuntu image, installed the necessary tools and committed the resulting snapshot into an image. I didn't use a Dockerfile to build this. Is that a problem?

**Comment by Krlier** [comment]
> @Krlier I started with an ubuntu image, installed the necessary tools and committed the resulting snapshot into an image. I didn't use a Dockerfile to build this. Is that a problem?

It would be great if you could also create a Dockerfile, this way someone could just build the image locally, without the need of pulling it from somewhere.

**Comment by sagar-cs03** [comment]
Ok, I will create a docker file and update you

**Comment by Krlier** [comment]
Hey @pedroespindula  and @sagar-cs03, I'm closing this issue for now due to the long inactivity.

If you're still working on this, please let me know and we'll reopen this issue! 🙂
