### ISSUE TITLE
Change the look of A6 - Vulnerable Wordpress Misconfig

### ISSUE THREAD

**Issue by Krlier** [globocom/secDevLabs#285]
The way [Vulnerable Wordpress Misconfig](https://github.com/globocom/secDevLabs/tree/master/owasp-top10-2017-apps/a6/misconfig-wordpress) is today, we are using this default look:

![image](https://user-images.githubusercontent.com/40367872/66075180-6a3c3680-e531-11e9-8d6b-edc203db8d6f.png)

It would be great if the app could have its own identity, just like all the other apps. Maybe changing the website to some kind of blog, company's page or some other cool idea!

**Comment by denisbrandl** [comment]
@Krlier Can you send me more information or sample from other app for custom this?

**Comment by Krlier** [comment]
> @Krlier Can you send me more information or sample from other app for custom this?

Hey @denisbrandl, thanks for the interest in working on this issue! 

Right now we don't have any other app featuring Wordpress for an example, but I did find a very interesting tutorial on how to change a theme [here](https://en.support.wordpress.com/themes/).

Since this month we are having Rock In Rio, I think it would be a great time to show our support to a local band in need of a website. What do you think of creating a perfect rock star web page? I already went ahead and found some free [templates](https://wordpress.org/themes/search/band/) that might look cool! 🎸🎶🤘

**Comment by mora50** [comment]
Can I get this one?

**Comment by rafaveira3** [comment]
Absolutely, @mora50! We will love to review any PR regarding this one! 🚀

**Comment by Krlier** [comment]
Hey @denisbrandl and @mora50, I'm closing this issue for now due to the long inactivity.

If you're still working on this, please let me know and we'll reopen this issue! 🙂
