### ISSUE TITLE
Add intentionally vulnerable mobile apps

### ISSUE THREAD

**Issue by Krlier** [globocom/secDevLabs#286]
Smartphones are everywhere nowadays and there are thousands of developers dedicated to creating new apps for them every day. With that in mind, it would be awesome with could help them by providing intentionally vulnerable mobile applications, so they could get to know better the most common vulnerabilities and how to fix them.

With that in mind, we could use [OWASP's mobile top 10 list](https://www.owasp.org/index.php/Mobile_Top_10_2016-Top_10) as a guide.
The topics featured in the list are:
* [M1-Improper Platform Usage](https://www.owasp.org/index.php/Mobile_Top_10_2016-M1-Improper_Platform_Usage)
* [M2-Insecure Data Storage](https://www.owasp.org/index.php/Mobile_Top_10_2016-M2-Insecure_Data_Storage)
* [M3-Insecure Communication](https://www.owasp.org/index.php/Mobile_Top_10_2016-M3-Insecure_Communication)
* [M4-Insecure Authentication](https://www.owasp.org/index.php/Mobile_Top_10_2016-M4-Insecure_Authentication)
* [M5-Insufficient Cryptography](https://www.owasp.org/index.php/Mobile_Top_10_2016-M5-Insufficient_Cryptography)
* [M6-Insecure Authorization](https://www.owasp.org/index.php/Mobile_Top_10_2016-M6-Insecure_Authorization)
* [M7-Poor Code Quality](https://www.owasp.org/index.php/Mobile_Top_10_2016-M7-Poor_Code_Quality)
* [M8-Code Tampering](https://www.owasp.org/index.php/Mobile_Top_10_2016-M8-Code_Tampering)
* [M9-Reverse Engineering](https://www.owasp.org/index.php/Mobile_Top_10_2016-M9-Reverse_Engineering)
* [M10-Extraneous Functionality](https://www.owasp.org/index.php/Mobile_Top_10_2016-M10-Extraneous_Functionality)

The new apps' path should be something along the lines of: `secDevLabs/owasp-top10-2016-mobile`.

**Comment by danielmitre** [comment]
I would like to try these, but I would have to build all 10 apps?

**Comment by Krlier** [comment]
Hey, @danielmitre! No! Just one is fine! 😁

Looking at this issue now, I think it's too broad, I'll break it into smaller ones. One for each app.

**Comment by danielmitre** [comment]
Thanks, I will go for some then.

**Comment by Krlier** [comment]
@danielmitre , I have broken down this issue in 10 others, separating each of the topics in an issue of its own.

You can find them here:

- [M1 - Improper Platform Usage app](https://github.com/globocom/secDevLabs/issues/307)
- [M2-Insecure Data Storage](https://github.com/globocom/secDevLabs/issues/308)
- [M3-Insecure Communication](https://github.com/globocom/secDevLabs/issues/309)
- [M4-Insecure Authentication](https://github.com/globocom/secDevLabs/issues/310)
- [M5-Insufficient Cryptography](https://github.com/globocom/secDevLabs/issues/311)
- [M6-Insecure Authorization](https://github.com/globocom/secDevLabs/issues/312)
- [M7-Poor Code Quality](https://github.com/globocom/secDevLabs/issues/313)
- [M8-Code Tampering](https://github.com/globocom/secDevLabs/issues/314)
- [M9-Reverse Engineering](https://github.com/globocom/secDevLabs/issues/315)
- [M10-Extraneous Functionality](https://github.com/globocom/secDevLabs/issues/316)
