### ISSUE TITLE
Refactoring app's directories and Create labels for each of them

### ISSUE THREAD

**Issue by vitoriario** [globocom/secDevLabs#296]
The current directory organization is a little confusing. We have the folder owasp-top10-2017-apps that has only OWASP Top 10 2017 vulnerability list. What about [OWASP API Security Top 10 2019](https://www.owasp.org/index.php/OWASP_API_Security_Project) (or another lists)? 
If we create a new folder for Top 10 2019 how would we handle with vulnerabilities that belongs to both lists?

**Comment by rafaveira3** [comment]
Hey, @vitoriario! Thanks a lot for reaching out! Great point! I guess we could rearrange our folder and `README.md` like the following: 

* `owasp-top-10-2017-web`
* `owasp-top-10-2019-api`
* `owasp-top-10-2016-mobile`
* `sans-top-25-2019-cwe`
* ...

What do you think? Do you have something in mind? 🙃

**Comment by vitoriario** [comment]
But what about same topics?
OWASP API Security 2019 and OWASP Top 10 2017 have Broken Authentication. How can we organize the apps?

**Comment by rafaveira3** [comment]
We could create a global folder called `apps` and inside each application README, we categorize them. "This app is related to `owasp-top-10-2017-web`, ` owasp-top-10-2019-api`".

An overall example of your main README.md could be something like this:

| Application | Type | Language | Labels |
| --- | --- | --- | --- | 
| CopyNPaste  | Web | Golang | `owasp-top-10-2017-web`, ` owasp-top-10-2019-api`|
| FlamengoApp  | Mobile | Java | `owasp-top-10-2016-mobile` |

What do you think? This would be a huge refactoring but it will indeed bring a lot of value to secDevLabs. I would love to review any PR regarding to this one! 🐼

**Comment by vitoriario** [comment]
Yes, makes sense! I think we can do this :)

**Comment by Krlier** [comment]
Hey, @vitoriario! Thanks for getting in touch!

I think the way the repository is structured today allows us to keep a history of all vulnerabilities lists. I know that in the future there might be new lists with intersecting topics, but I believe this is a cool feature, as we can keep track of vulnerable apps throughout time. 

If a new list is released and we feel like adding it to secDevLabs, I think we should create a whole new range of apps, this way the lab only gets richer with a bigger array of vulnerabilities in different scenarios.

If we only have an `apps` folder, we would need to keep updating the apps and their README's with every list released, which might not be a good idea.

What do you guys think?

**Comment by vitoriario** [comment]
But create a global "apps" folder does not stop us from create new apps.
I think if two lists has the same vulnerability the apps related to this topic should be present in both lists.

I feel it's like we "waste" apps if we don't include them in every list they belong to. Also, it can get confusing having multiple folders with same type of vulnerabilities.

**Comment by vitoriario** [comment]
Also, the history of all vulnerabilities lists can be kept in README.

For example:

#### OWASP Web Top 10 2017:

|  | Vulnerability |  app |
|--|--|--|
| A1 | Injection |  CopyNPaste  |
| ... | ... |  ...  |

**Comment by Krlier** [comment]
> But create a global "apps" folder does not stop us from create new apps.
> I think if two lists has the same vulnerability the apps related to this topic should be present in both lists.
> 
> I feel it's like we "waste" apps if we don't include them in every list they belong to. Also, it can get confusing having multiple folders with same type of vulnerabilities.

Ok, I get what you're saying, but how many lists are there? By doing this we need to be up to date with all the lists being released and not only that, we need to be sure our app falls into that list's vulnerability description.

I don't think it gets confusing having multiple folders for each list, as each one of them should only address a specific year.

**Comment by vitoriario** [comment]
> Ok, I get what you're saying, but how many lists are there?  By doing this we need to be up to date with all the lists being released and not only that, we need to be sure our app falls into that list's vulnerability description.

But our goal is cover as many OWASP lists as we can, isn't?

Also, I think is very easy to know if a created app falls into that list's vulnerability (easier than create a new one :p).


> I don't think it gets confusing having multiple folders for each list, as each one of them should only address a specific year.

As I said before, It can be a "waste" of apps.

I'll give you an example:
Let's suppose that a new Web Top 10 list is released today: OWASP Web Top 10 2019 with some of same vulnerabilities of 2017 (for example, Broken Authentication) but in a different order.

A new student wants to study using the most recently list, but he/she has to visit owasp top 10 2017 folder to get Broken Authentication app... :(
Even if we create a new Broken Authentication app, would not be cool if we give to this student the opportunity to training with all apps related to the topic?

**Comment by Krlier** [comment]
@vitoriario, ok. I understand what you're saying. 

But how would we organize the apps now?

Do you think maybe a table with the vulnerability description, which list it fits and its name?

**Comment by vitoriario** [comment]
Hi @Krlier, sorry it took me so long to reply.
We could follow @rafaveira3 suggestion. If it gets confusing we could discuss another solution, ok?

Let's create another branch and test if this new organization will be better :)

**Comment by rafaveira3** [comment]
Hey, guys! I am closing this one for long inactivity. Feel free to reopen it if you still want to discuss more the structure of the project. 🙃
