### ISSUE TITLE
Docker complains about the projet name

### ISSUE THREAD

**Issue by Nooguat** [globocom/secDevLabs#571]
What are the steps to reproduce this bug?
-------------------------------------------
1. Try to start any lab with the make install command

What happens?
-------------
 The lab crash with this docker error `secDevLabs is not a valid project name`

What were you expecting to happen?
----------------------------------
The lab spins up

If this is any help. I'm using the last Arch Linux build; with docker and docker-compose installed from pacman

**Comment by fguisso** [comment]
Hey @Nooguat can you provide more information before we test your case?
Run the following commands and paste the output here, please.
`docker version`
`docker-compose version`

We made some new features, remember to make your local repository up to date.

**Comment by ragoso** [comment]
[This docker issue](https://github.com/docker/compose/issues/9519) may be related.

**Comment by ragoso** [comment]
#577 to support changes in https://github.com/docker/compose/pull/9385
