### ISSUE TITLE
Add guidelines on how to install dirb 

### ISSUE THREAD

**Issue by rafaveira3** [globocom/secDevLabs#80]
This tool is used in `Amarelo Designs` attack narrative and it would be great if we have instructions on how to install it on OSX.

**Comment by rafaveira3** [comment]
Or maybe we could change the narrative to use another similar tool that may be easier to use.

**Comment by pedrokiefer** [comment]
Try this:

```
curl -L -O https://sourceforge.net/projects/dirb/files/dirb/2.22/dirb222.tar.gz/download
tar xvzf dirb222.tar.gz
chmod 766 dirb222
cd dirb222
find . -type d -exec chmod 766 {} \;
chmod +x configure
./configure
make && make install
```

**Comment by Krlier** [comment]
Thanks for your contribution @pedrokiefer! I'll look into it!
